require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/*
    - vendor/**/*
  NewCops: enable

Style/FormatStringToken:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

RSpec/FilePath:
  SpecSuffixOnly: true

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Metrics:
  Enabled: false
