name: RSpec

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  rspec:
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-10.15, windows-2019 ]
        ruby: [ 2.5, 2.6.6, 2.7 ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install dependencies
      run: bundle install
    - name: Test and publish code coverage
      run: bundle exec rake
    - name: Upload coverage
      if: ${{ matrix.ruby == 2.7 && matrix.os == 'ubuntu-20.04' }}
      uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      coverageCommand: echo "Uploading coverage"
      coverageLocations: ./coverage/.resultset.json:json
        